name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Clone the repository via SSH and navigate to the correct directory
      - name: Deploy & Clone Repository
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            if [ ! -d "/root/GOPAT" ]; then
              git clone https://Narniii:${{ secrets.ACCESS_TOKEN }}@github.com/Narniii/GOPAT.git
            fi
            cd GOPAT
            git pull origin main
            pwd
      
      # Step 2: Run npm install to set up the dependencies
      - name: Install NPM Dependencies
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd /root/GOPAT
            /usr/local/bin/npm install

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      # Step 3: Run npm build after dependencies are installed
      - name: Build Project
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd /root/GOPAT
            /usr/local/bin/npm run build
